language: python
before_install:
  - wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O ~/miniconda.sh
  - bash ~/miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - conda create -y -n pytorch-crf python=3.6
  - source activate pytorch-crf
  - conda install -y -c pytorch pytorch=0.3.0
install:
  - pip install -r requirements.txt
  - pip install .
script: pytest --cov
after_success: coveralls
